// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCezjeqfGQ_7ME3iOXw0w00lkCQF6cSae4',
    appId: '1:60698621398:web:562db793561c1d38bf6077',
    messagingSenderId: '60698621398',
    projectId: 'food-delivery-8e2af',
    authDomain: 'food-delivery-8e2af-ed500.firebaseapp.com',
    storageBucket: 'food-delivery-8e2af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbWTkz6YEPLilshkYq-MwoGVwTlvvGFG8',
    appId: '1:60698621398:android:f3b87ff6f69c905abf6077',
    messagingSenderId: '60698621398',
    projectId: 'food-delivery-8e2af',
    storageBucket: 'food-delivery-8e2af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Ib9cEDGXdYskKxfK9-5P0FY_Alo_jWY',
    appId: '1:60698621398:ios:58fd1e2855c08859bf6077',
    messagingSenderId: '60698621398',
    projectId: 'food-delivery-8e2af',
    storageBucket: 'food-delivery-8e2af.appspot.com',
    iosBundleId: 'com.djjambread.jammybread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Ib9cEDGXdYskKxfK9-5P0FY_Alo_jWY',
    appId: '1:60698621398:ios:eec770acfeed6139bf6077',
    messagingSenderId: '60698621398',
    projectId: 'food-delivery-8e2af',
    storageBucket: 'food-delivery-8e2af.appspot.com',
    iosBundleId: 'com.djjambread.foodDelivery.RunnerTests',
  );
}
